sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t midemarc/juridico_back .

script:
  - echo "coucou"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master