sudo: required

#language: python

#python:
#    - "3.6"

services:
  - docker

before_install:
  - docker build -t midemarc/juridico_back .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master