# Generated by Django 2.0.2 on 2018-02-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camarade',
            fields=[
                ('resid', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pseudo', models.CharField(max_length=128, unique=True)),
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('courriel', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('resid', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(default='')),
                ('quand', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('resid', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(default='')),
                ('nom', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('resid', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(default='')),
                ('nom', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=128, unique=True)),
                ('question', models.TextField()),
                ('reponse_type', models.CharField(choices=[('t', 'textuel'), ('e', 'entier numérique'), ('f', 'numérique à décimales'), ('b', 'booléen'), ('d', 'date')], max_length=1)),
                ('methode', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('repid', models.AutoField(primary_key=True, serialize=False)),
                ('reponse', models.CharField(max_length=1024)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('reqid', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('description_cas', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=32)),
                ('valeur', models.CharField(max_length=1024)),
                ('reponse_type', models.CharField(choices=[('t', 'textuel'), ('e', 'entier numérique'), ('f', 'numérique à décimales'), ('b', 'booléen'), ('d', 'date')], max_length=1)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Requete')),
            ],
        ),
        migrations.AddField(
            model_name='reponse',
            name='requete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Requete'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='tags',
            field=models.ManyToManyField(to='juridico.Tag'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='tags',
            field=models.ManyToManyField(to='juridico.Tag'),
        ),
        migrations.AddField(
            model_name='direction',
            name='tags',
            field=models.ManyToManyField(to='juridico.Tag'),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(to='juridico.Tag'),
        ),
        migrations.AddField(
            model_name='camarade',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Client'),
        ),
        migrations.AddField(
            model_name='camarade',
            name='tags',
            field=models.ManyToManyField(to='juridico.Tag'),
        ),
    ]
