# Generated by Django 2.0.2 on 2018-02-24 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pseudo', models.CharField(max_length=128, unique=True)),
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('courriel', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=128, unique=True)),
                ('question', models.TextField()),
                ('reponse_type', models.CharField(choices=[('t', 'textuel'), ('e', 'entier numérique'), ('f', 'numérique à décimales'), ('b', 'booléen')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('repid', models.IntegerField(primary_key=True, serialize=False)),
                ('reponse', models.CharField(max_length=1024)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('reqid', models.IntegerField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('description_cas', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Client')),
            ],
        ),
        migrations.AddField(
            model_name='reponse',
            name='requete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Requete'),
        ),
    ]
