# Generated by Django 2.0.2 on 2018-02-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(default=[], to='juridico.Tag'),
        ),
    ]
