# Generated by Django 2.0.2 on 2018-02-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='reponse_type',
            new_name='response_type',
        ),
    ]
