# Generated by Django 2.0.2 on 2018-02-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0002_auto_20180224_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='response_type',
            new_name='reponse_type',
        ),
    ]
