# Generated by Django 2.0.2 on 2018-02-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0002_auto_20180225_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camarade',
            name='tags',
            field=models.ManyToManyField(blank=True, to='juridico.Tag'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, to='juridico.Tag'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='juridico.Tag'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='juridico.Tag'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='juridico.Tag'),
        ),
    ]
