# Generated by Django 2.0.2 on 2018-02-25 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0003_auto_20180224_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('dirid', models.IntegerField(primary_key=True, serialize=False)),
                ('quand', models.CharField(max_length=256)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('resid', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('vid', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=32)),
                ('valeur', models.CharField(max_length=1024)),
                ('reponse_type', models.CharField(choices=[('t', 'textuel'), ('e', 'entier numérique'), ('f', 'numérique à décimales'), ('b', 'booléen'), ('d', 'date')], max_length=1)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Requete')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='methode',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponse_type',
            field=models.CharField(choices=[('t', 'textuel'), ('e', 'entier numérique'), ('f', 'numérique à décimales'), ('b', 'booléen'), ('d', 'date')], max_length=1),
        ),
        migrations.CreateModel(
            name='Camarade',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='juridico.Ressource')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Client')),
            ],
            bases=('juridico.ressource',),
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='juridico.Ressource')),
                ('nom', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=1024)),
            ],
            bases=('juridico.ressource',),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='juridico.Ressource')),
                ('nom', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=1024)),
            ],
            bases=('juridico.ressource',),
        ),
        migrations.AddField(
            model_name='ressource',
            name='requete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.Requete'),
        ),
    ]
