# Generated by Django 2.0.2 on 2018-02-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0004_ressourcederequete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='methode',
        ),
    ]
