# Generated by Django 2.0.2 on 2018-02-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0005_remove_question_methode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contenu_liste',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponse_type',
            field=models.CharField(choices=[('t', 'textuel'), ('e', 'entier numérique'), ('f', 'numérique à décimales'), ('b', 'booléen'), ('d', 'date'), ('l', 'liste')], max_length=1),
        ),
    ]
