# Generated by Django 2.0.2 on 2018-02-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0007_auto_20180225_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='client',
        ),
    ]
