# Generated by Django 2.0.2 on 2018-02-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0008_remove_reponse_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressourcederequete',
            name='id',
        ),
        migrations.AlterField(
            model_name='ressourcederequete',
            name='rrid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
