# Generated by Django 2.0.2 on 2018-02-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0009_auto_20180225_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourcederequete',
            name='resid',
            field=models.IntegerField(default=-1),
        ),
    ]
