# Generated by Django 2.0.2 on 2018-03-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0010_ressourcederequete_resid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='contenu_liste',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='reponse_type',
        ),
    ]
