# Generated by Django 2.0.2 on 2018-03-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0011_auto_20180304_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='nom',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
