# Generated by Django 2.0.2 on 2018-03-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0012_auto_20180304_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressourcederequete',
            old_name='poid',
            new_name='poids',
        ),
    ]
