# Generated by Django 2.0.2 on 2018-03-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0012_auto_20180304_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=1024)),
                ('parent', models.ManyToManyField(to='juridico.Categorie')),
            ],
        ),
        migrations.AddField(
            model_name='camarade',
            name='code_postal',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='camarade',
            name='commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='adresse',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='organisation',
            name='appartenance',
            field=models.CharField(blank=True, help_text='Par exemple, pour un·e avocat·e ou notaire, son cabinet.', max_length=1024),
        ),
        migrations.AddField(
            model_name='organisation',
            name='code_postal',
            field=models.CharField(blank=True, help_text='Sert à géolocaliser', max_length=6),
        ),
        migrations.AddField(
            model_name='organisation',
            name='commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='courriel',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='organisation',
            name='heures_ouverture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='site_web',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='organisation',
            name='telecopieur',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='organisation',
            name='telephone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
