# Generated by Django 2.0.2 on 2018-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0013_auto_20180310_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
