# Generated by Django 2.0.2 on 2018-03-10 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0015_auto_20180310_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('ttid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='type_de_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juridico.TagType'),
        ),
    ]
