# Generated by Django 2.0.2 on 2018-03-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0017_remove_organisation_site_web'),
        ('juridico', '0013_auto_20180310_1719'),
    ]

    operations = [
    ]
