# Generated by Django 2.0.2 on 2018-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0019_auto_20180311_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourcederequete',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
