# Generated by Django 2.0.2 on 2018-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0021_auto_20180311_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='identifiant',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
