# Generated by Django 2.0.2 on 2018-03-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0022_direction_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='quand',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
