# Generated by Django 2.0.2 on 2018-03-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0023_auto_20180311_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='variables',
            field=models.TextField(default='', help_text='Les variables sont séparées par des espaces'),
        ),
        migrations.AddField(
            model_name='requete',
            name='ip',
            field=models.CharField(default='132.208.170.58', max_length=64),
        ),
    ]
