# Generated by Django 2.0.2 on 2018-03-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0013_auto_20180310_1719'),
        ('juridico', '0024_auto_20180311_1245'),
    ]

    operations = [
    ]
