# Generated by Django 2.0.2 on 2018-03-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0026_auto_20180311_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='nom',
            field=models.CharField(max_length=32),
        ),
    ]
