# Generated by Django 2.0.2 on 2018-03-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0018_merge_20180311_1128'),
        ('juridico', '0027_auto_20180311_1442'),
    ]

    operations = [
    ]
