# Generated by Django 2.0.2 on 2018-03-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0027_auto_20180311_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='camarade',
            name='type_classe',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='direction',
            name='type_classe',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='documentation',
            name='type_classe',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organisation',
            name='type_classe',
            field=models.CharField(default='', max_length=32),
        ),
    ]
