# Generated by Django 2.0.2 on 2018-03-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0028_auto_20180311_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourcederequete',
            name='type_classe',
            field=models.CharField(default='', max_length=32),
        ),
    ]
