# Generated by Django 2.0.2 on 2018-03-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0029_ressourcederequete_type_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camarade',
            name='type_classe',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='direction',
            name='type_classe',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='type_classe',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type_classe',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='ressourcederequete',
            name='type_classe',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
