# Generated by Django 2.0.2 on 2018-03-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0028_merge_20180311_1710'),
        ('juridico', '0030_auto_20180311_1748'),
    ]

    operations = [
    ]
