# Generated by Django 2.0.2 on 2018-03-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0031_merge_20180327_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressourcederequete',
            old_name='poid',
            new_name='poids',
        ),
    ]
