# Generated by Django 2.0.2 on 2018-04-02 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0032_auto_20180331_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='camarade',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description de la ressource (anglais)'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom_en',
            field=models.CharField(blank=True, help_text='Nom de la catégorie (anglais)', max_length=1024),
        ),
        migrations.AddField(
            model_name='client',
            name='langue',
            field=models.CharField(blank=True, choices=[('fr', 'français'), ('en', 'english')], max_length=2),
        ),
        migrations.AddField(
            model_name='direction',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description de la ressource (anglais)'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='categorie_educaloi_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description de la ressource (anglais)'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='nom_en',
            field=models.CharField(blank=True, help_text='Nom du document (anglais)', max_length=256),
        ),
        migrations.AddField(
            model_name='documentation',
            name='url_en',
            field=models.CharField(blank=True, help_text='URL du document (anglais)', max_length=1024),
        ),
        migrations.AddField(
            model_name='docusource',
            name='nom_en',
            field=models.CharField(blank=True, help_text='Nom de la source (anglais)', max_length=256),
        ),
        migrations.AddField(
            model_name='docusource',
            name='url_en',
            field=models.CharField(blank=True, help_text='Nom de la source (anglais)', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='appartenance_en',
            field=models.CharField(blank=True, help_text='Par exemple, pour un·e avocat·e ou notaire, son cabinet.', max_length=1024),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description de la ressource (anglais)'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='heures_ouverture_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='nom_en',
            field=models.CharField(blank=True, help_text="Nom de l'organisme (anglais)", max_length=256),
        ),
        migrations.AddField(
            model_name='organisation',
            name='url_en',
            field=models.CharField(blank=True, help_text="URL de l'organisme (anglais)", max_length=1024),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(blank=True, help_text="Question posée à l'usager·e (anglais)."),
        ),
        migrations.AddField(
            model_name='tag',
            name='nom_en',
            field=models.CharField(blank=True, help_text='Nom du tag (anglais)', max_length=256),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='nom_en',
            field=models.CharField(blank=True, help_text='Nom du type de tag (anglais)', max_length=256),
        ),
        migrations.AlterField(
            model_name='camarade',
            name='code_postal',
            field=models.CharField(blank=True, help_text='Sert à géolocaliser.', max_length=7, validators=[django.core.validators.RegexValidator(message='Format invalide pour un code postal. Le format est: X0X 0X0, où X est une lettre et 0 un chiffre.', regex='^[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]$')]),
        ),
        migrations.AlterField(
            model_name='camarade',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la ressource (français)'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(help_text='Nom de la catégorie (français)', max_length=1024),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postal',
            field=models.CharField(blank=True, help_text='Sert à géolocaliser.', max_length=7, validators=[django.core.validators.RegexValidator(message='Format invalide pour un code postal. Le format est: X0X 0X0, où X est une lettre et 0 un chiffre.', regex='^[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]$')]),
        ),
        migrations.AlterField(
            model_name='direction',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la ressource (français)'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la ressource (français)'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='nom',
            field=models.CharField(help_text='Nom du document (français)', max_length=256),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='url',
            field=models.CharField(help_text='URL du document (français)', max_length=102),
        ),
        migrations.AlterField(
            model_name='docusource',
            name='nom',
            field=models.CharField(help_text='Nom de la source (français)', max_length=256),
        ),
        migrations.AlterField(
            model_name='docusource',
            name='url',
            field=models.CharField(blank=True, help_text='Nom de la source (français)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='code_postal',
            field=models.CharField(blank=True, help_text='Sert à géolocaliser.', max_length=7, validators=[django.core.validators.RegexValidator(message='Format invalide pour un code postal. Le format est: X0X 0X0, où X est une lettre et 0 un chiffre.', regex='^[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]$')]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la ressource (français)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='nom',
            field=models.CharField(help_text="Nom de l'organisme (français)", max_length=256),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='url',
            field=models.CharField(blank=True, help_text="URL de l'organisme (français)", max_length=1024),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text="Question posée à l'usager·e (français)."),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nom',
            field=models.CharField(help_text='Nom du tag (français)', max_length=256),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='nom',
            field=models.CharField(help_text='Nom du type de tag (français)', max_length=256),
        ),
    ]
