# Generated by Django 2.0.2 on 2018-04-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0033_auto_20180402_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camarade',
            name='code_postal',
        ),
    ]
