#!/bin/sh

# Set these paths appropriately

BIN=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/bin
CMD=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/cmd
LIB=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
