#!/bin/sh

# Set these paths appropriately

BIN=/home/mok/src/treetagger-install/bin
CMD=/home/mok/src/treetagger-install/cmd
LIB=/home/mok/src/treetagger-install/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
