#!/bin/sh

# Set these paths appropriately

BIN=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/bin
CMD=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/cmd
LIB=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
