#!/bin/sh

# Set these paths appropriately

BIN=/home/mok/src/treetagger-install/bin
CMD=/home/mok/src/treetagger-install/cmd
LIB=/home/mok/src/treetagger-install/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
