#!/bin/sh

# Set these paths appropriately

BIN=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/bin
CMD=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/cmd
LIB=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
