#!/bin/sh

# Set these paths appropriately

BIN=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/bin
CMD=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/cmd
LIB=/home/mok/Sync/Projets/Juridico/Juridico/treetagger-install/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
